[config] Allow setting config keys on command line.
   - config keys can be set on command line

      e.g. git-slack-hook -c hooks.slack.show-full-commit true

      Values set on the repo will take precedence. This allows minimal
      per-repository git configuration, with sensible global defaults to
      be set in a common hook. (with gitolite use case in mind).

diff --git a/git-slack-hook b/git-slack-hook
--- a/git-slack-hook
+++ b/git-slack-hook
@@ -30,6 +30,57 @@ function help() {
   echo " git config hooks.slack.branch-regexp 'regexp'  #optional"
 }
 
+# Per-Repo config override these defaults
+DEFAULTS=(
+  #KEY                              #VALUE
+  hooks.slack.show-only-last-commit "false"
+  hooks.slack.show-full-commit      "false"
+)
+
+function git_config() {
+  # Usage: git_config KEY
+  #   prints git config value if found.
+  #
+  #   exits with success is found, failure otherwise.
+  #   the return value allows differentiating undefined keys from empty values.
+
+  # try repo config first, then search defaults
+  local i=0
+  git config "$1" 2>/dev/null || {
+    # try defaults (program defaults and command line)
+    for ((i=0; i<${#DEFAULTS[@]}; i+=2)); do
+      if [[ "${DEFAULTS[i]}" == "$1" ]]; then echo -n "${DEFAULTS[i+1]}"; return 0; fi
+    done
+    return 1
+  }
+}
+
+function git_config_bool() {
+  local val=$(git_config "$1")
+  case "${val^^}" in
+    ''|0|FALSE|NO|N)
+      echo -n "false"
+      ;;
+    *)
+      echo -n "true"
+      ;;
+  esac
+}
+
+function update_defaults() {
+  # update_defaults KEY VAL
+  local i=0
+  for ((i=0; i<${#DEFAULTS[@]}; i+=2)); do
+    if [[ "${DEFAULTS[i]}" == "$1" ]]; then
+      DEFAULTS[i]="$2"
+      return 0
+    fi
+  done
+  DEFAULTS+=("$1" "$2")
+  return 0
+}
+
+
 function replace_variables() {
   sed "s|%repo_path%|$repopath|g;s|%old_rev_hash%|$oldrev|g;s|%new_rev_hash%|$newrev|g;s|%rev_hash%|$newrev|g;s|%repo_prefix%|$repoprefix|g"
 }
@@ -156,14 +207,12 @@ function notify() {
       ;;
   esac
 
-  branchregexp=$(git config --get hooks.slack.branch-regexp)
+  branchregexp=$(git_config hooks.slack.branch-regexp)
   if [ -n "$branchregexp" ]; then
     if [[ ! $short_refname =~ $branchregexp ]]; then
       exit 0;
     fi
   fi
-
-  #channels=$(git config hooks.irc.channel)
 
   # plural suffix, default "", changed to "s" if commits > 1
   s=""
@@ -182,10 +231,9 @@ function notify() {
     repo=${repodir%.git}
   fi
 
-  repoprefix=$(git config hooks.slack.repo-nice-name || git config hooks.irc.prefix || git config hooks.emailprefix || echo "$repo")
-  onlylast=$(git config --get hooks.slack.show-only-last-commit)
-  onlylast=$onlylast && [ -n "$onlylast" ]
-  fullcommit=$(git config --get hooks.slack.show-full-commit)
+  repoprefix=$(git_config hooks.slack.repo-nice-name || git_config hooks.irc.prefix || git_config hooks.emailprefix || echo "$repo")
+  fullcommit=$(git_config_bool hooks.slack.show-full-commit)
+  onlylast=$(git_config_bool hooks.slack.show-only-last-commit)
 
   # Get the user information
   # If $GL_USER is set we're running under gitolite.
@@ -225,15 +273,15 @@ function notify() {
       ;;
   esac
 
-  if $onlylast && [[ "${change_type}" != "delete" ]]; then
+  if [[ "$onlylast" == true ]] && [[ "${change_type}" != "delete" ]]; then
     header="$header, showing last $single_commit_suffix:"
   fi
 
 
   if [[ "${change_type}" != "delete" && "${refname_type}" == "branch" ]]; then
-    changeseturlpattern=$(git config --get hooks.slack.changeset-url-pattern)
-    compareurlpattern=$(git config --get hooks.slack.compare-url-pattern)
-    reporoot=$(git config --get hooks.slack.repos-root)
+    changeseturlpattern=$(git_config hooks.slack.changeset-url-pattern)
+    compareurlpattern=$(git_config hooks.slack.compare-url-pattern)
+    reporoot=$(git_config hooks.slack.repos-root)
 
     urlformat=
     if [ -n "$changeseturlpattern" -a -n "$reporoot" ]; then
@@ -277,7 +325,7 @@ function notify() {
 
 
     # merge `git log` output with $header
-    if $onlylast; then
+    if [[ "$onlylast" == true ]]; then
       countarg="-n 1"
     else
       countarg=""
@@ -323,11 +371,11 @@ function notify() {
 "text": '"$(json_string "${header}")"
   fi
 
-  webhook_url=$(git config --get hooks.slack.webhook-url)
-  channel=$(git config --get hooks.slack.channel)
-  username=$(git config --get hooks.slack.username)
-  iconurl=$(git config --get hooks.slack.icon-url)
-  iconemoji=$(git config --get hooks.slack.icon-emoji)
+  webhook_url=$(git_config hooks.slack.webhook-url)
+  channel=$(git_config hooks.slack.channel)
+  username=$(git_config hooks.slack.username)
+  iconurl=$(git_config hooks.slack.icon-url)
+  iconemoji=$(git_config hooks.slack.icon-emoji)
 
   if [ -z "$webhook_url" ]; then
     echo "ERROR: config settings not found"
@@ -357,6 +405,32 @@ function notify() {
 
 }
 
+while [[ "$#" -gt 0 ]]; do
+  case "$1" in
+    -h|--help)
+      help
+      exit 1
+      ;;
+    -c|--config)
+      [[ "$#" -gt 2 ]] || { echo >&2 "Missing arguments: syntax is `--config <key> <value>`"; exit 1; }
+      update_defaults "$2" "$3"
+      shift 2
+      ;;
+    -d|--debug)
+      DEBUG=1
+      ;;
+    --trace)
+      set -x
+      ;;
+    --*)
+      echo >&2 "Invalid flag: $1"
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+DEBUG="${DEBUG:-}"
 # MAIN PROGRAM
 # Read all refs from stdin, notify slack for each
 while read line; do
